import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Sidebars mirror the previous mkdocs SUMMARY.md tabs:
 *   docs        -> "Guides" + "About"
 *   cli         -> generated CLI reference (autogenerated from docs/cli)
 *   developers  -> Library, API reference (autogenerated), Architecture, Development
 */
const sidebars: SidebarsConfig = {
  docs: [
    'index',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/installation',
        'getting-started/configuration',
        'getting-started/quick-start',
        'getting-started/exit-codes-and-output',
      ],
    },
    'concepts/how-prisma-airs-works',
    {
      type: 'category',
      label: 'Runtime Security',
      items: [
        'runtime/overview',
        'runtime/scanning',
        'runtime/config-management',
        {
          type: 'category',
          label: 'Guardrail Optimization',
          items: [
            'runtime/guardrails/overview',
            'runtime/guardrails/generate-and-evaluate',
            'runtime/guardrails/metrics',
            'runtime/guardrails/topic-constraints',
          ],
        },
        {
          type: 'category',
          label: 'DLP',
          items: [
            'runtime/dlp/overview',
            'runtime/dlp/filtering-profiles',
            'runtime/dlp/patterns',
            'runtime/dlp/profiles',
            'runtime/dlp/dictionaries',
            'runtime/dlp/generate',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'AI Red Teaming',
      items: [
        'redteam/overview',
        'redteam/end-to-end-walkthrough',
        'redteam/scanning',
        'redteam/targets',
        'redteam/infrastructure',
        'redteam/prompt-sets',
        'redteam/guardrail-to-redteam',
      ],
    },
    {
      type: 'category',
      label: 'AI Gateway',
      link: { type: 'doc', id: 'cli/aigateway/resources' },
      items: ['cli/aigateway/workspaces', 'cli/aigateway/telemetry'],
    },
    {
      type: 'category',
      label: 'Model Security',
      items: [
        'model-security/overview',
        'model-security/groups',
        'model-security/rules',
        'model-security/scans',
        'model-security/labels',
      ],
    },
    {
      type: 'category',
      label: 'DLP Detection Testing',
      items: ['dlp-detection/index', 'dlp-detection/catalog', 'dlp-detection/svg-dlp-bypass'],
    },
    {
      type: 'category',
      label: 'Backup & Restore',
      items: ['backup/overview'],
    },
    {
      type: 'category',
      label: 'Reference',
      items: ['reference/configuration', 'reference/environment-variables'],
    },
    {
      type: 'category',
      label: 'About',
      items: ['about/release-notes', 'about/flag-migration', 'about/license'],
    },
  ],

  cli: [{ type: 'autogenerated', dirName: 'cli' }],

  developers: [
    {
      type: 'category',
      label: 'Library',
      items: [
        'developers/library/getting-started',
        'developers/library/recipes',
        'model-security/install',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [{ type: 'autogenerated', dirName: 'developers/api' }],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: ['architecture/overview', 'architecture/core-loop', 'architecture/design-decisions'],
    },
    {
      type: 'category',
      label: 'Development',
      items: [
        'developers/ai-gateway-command-plan',
        'development/contributing',
        'development/testing',
        'development/local-setup',
        'development/full-cli-sweep',
        'development/smoke-tests',
      ],
    },
    {
      type: 'category',
      label: 'Advanced Reference',
      items: ['reference/airs-constraints', 'reference/agent-instructions'],
    },
  ],
};

export default sidebars;
