import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { buildProgram } from '../src/cli/program.js';
import { loadExamples } from './cli-docs/examples.js';
import { renderGroupPage, renderIndex } from './cli-docs/render.js';
import { collectPages, walkProgram } from './cli-docs/walk.js';

const OUT_DIR = 'docs-site/docs/cli';
const EXAMPLES_DIR = 'docs-site/cli-examples';
const GROUP_DIRS = ['runtime', 'redteam', 'model-security'];

// Docusaurus autogenerated-sidebar category labels + ordering for each generated subdirectory.
const CATEGORY_LABELS: Record<string, string> = {
  runtime: 'Runtime',
  redteam: 'Red Team',
  'model-security': 'Model Security',
  dlp: 'DLP',
  topics: 'Topics',
};
const CATEGORY_POSITION: Record<string, number> = {
  runtime: 1,
  redteam: 2,
  'model-security': 3,
};

function humanize(dir: string): string {
  return (
    CATEGORY_LABELS[dir] ??
    dir
      .split('-')
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
      .join(' ')
  );
}

function writeCategoryFile(outDir: string, relDir: string): void {
  const base = relDir.split('/').pop() ?? relDir;
  const meta: Record<string, unknown> = { label: humanize(base) };
  if (CATEGORY_POSITION[base] !== undefined) meta.position = CATEGORY_POSITION[base];
  const file = join(outDir, relDir, '_category_.json');
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, `${JSON.stringify(meta, null, 2)}\n`);
}

export function generate(outDir = OUT_DIR, examplesDir = EXAMPLES_DIR): string[] {
  // Clear previously generated group subtrees (keep index.md handling explicit).
  for (const g of GROUP_DIRS) rmSync(join(outDir, g), { recursive: true, force: true });

  const pages = collectPages(walkProgram(buildProgram()));
  const examples = loadExamples(examplesDir);

  const written: string[] = [];
  const seenDirs = new Set<string>();
  for (const page of pages) {
    const file = join(outDir, `${page.slug}.md`);
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, renderGroupPage(page, examples));
    written.push(file);
    // Track every directory segment so each generated category gets a label file.
    const segments = page.slug.split('/');
    segments.pop(); // drop filename
    for (let i = 0; i < segments.length; i++) {
      const relDir = segments.slice(0, i + 1).join('/');
      if (!seenDirs.has(relDir)) {
        seenDirs.add(relDir);
        writeCategoryFile(outDir, relDir);
        written.push(join(outDir, relDir, '_category_.json'));
      }
    }
  }

  const indexFile = join(outDir, 'index.md');
  writeFileSync(indexFile, renderIndex(pages));
  written.push(indexFile);
  return written;
}

// Run when invoked directly via tsx.
if (import.meta.url === `file://${process.argv[1]}`) {
  const files = generate();
  console.log(`Generated ${files.length} CLI reference files.`);
}
