import type { Command } from 'commander';
import { examples } from '../examples.js';
import { usageError } from '../renderer/index.js';

/**
 * Static shell completion generation.
 *
 * Commander has no built-in completion generator, so we walk the command tree
 * and emit a static script per shell: each node in the tree becomes a case in
 * a path → suggestions lookup covering subcommand names (plus aliases) and
 * visible long flags. Positional argument values are not completed.
 *
 * The generators are pure (Command → script string) so they can be unit
 * tested without touching a shell.
 */

export const COMPLETION_SHELLS = ['bash', 'zsh', 'fish'] as const;
export type CompletionShell = (typeof COMPLETION_SHELLS)[number];

export interface CompletionNode {
  /** Space-joined command path below the program root; '' for the root. */
  path: string;
  /** Suggestions at this path: subcommand names, aliases, visible long flags. */
  words: string[];
}

/** Walk the command tree collecting one suggestion node per command path. */
export function collectCompletionNodes(root: Command, path: string[] = []): CompletionNode[] {
  const words: string[] = [];
  for (const sub of root.commands) {
    words.push(sub.name(), ...sub.aliases());
  }
  for (const opt of root.options) {
    if (!opt.hidden && opt.long) words.push(opt.long);
  }
  words.push('--help');

  const node: CompletionNode = { path: path.join(' '), words: [...new Set(words)] };
  const children = root.commands.flatMap((sub) =>
    collectCompletionNodes(sub, [...path, sub.name()]),
  );
  return [node, ...children];
}

function programName(root: Command): string {
  return root.name() || 'airs';
}

export function generateBashCompletion(root: Command): string {
  const name = programName(root);
  const cases = collectCompletionNodes(root)
    .map((n) => `    '${n.path}') words="${n.words.join(' ')}" ;;`)
    .join('\n');

  return `#!/usr/bin/env bash
# Bash completion for ${name} (Prisma AIRS CLI). Generated by \`${name} completion bash\`.
#
# Install: ${name} completion bash > ~/.local/share/bash-completion/completions/${name}
#   or:    echo 'source <(${name} completion bash)' >> ~/.bashrc

_${name}_completions() {
  local cur path i w words
  cur="\${COMP_WORDS[COMP_CWORD]}"
  path=""
  for ((i = 1; i < COMP_CWORD; i++)); do
    w="\${COMP_WORDS[i]}"
    [[ "$w" == -* ]] && continue
    path="\${path:+$path }$w"
  done
  words=""
  case "$path" in
${cases}
    *) words="" ;;
  esac
  COMPREPLY=( $(compgen -W "$words" -- "$cur") )
}
complete -F _${name}_completions ${name}
`;
}

export function generateZshCompletion(root: Command): string {
  const name = programName(root);
  const cases = collectCompletionNodes(root)
    .map((n) => `    '${n.path}') completions=(${n.words.join(' ')}) ;;`)
    .join('\n');

  return `#compdef ${name}
# Zsh completion for ${name} (Prisma AIRS CLI). Generated by \`${name} completion zsh\`.
#
# Install: mkdir -p ~/.zfunc && ${name} completion zsh > ~/.zfunc/_${name}
#   then in ~/.zshrc (before compinit): fpath+=(~/.zfunc)
#   and ensure: autoload -Uz compinit && compinit

_${name}() {
  local -a completions
  local path="" w
  for w in "\${(@)words[2,CURRENT-1]}"; do
    [[ "$w" == -* ]] && continue
    path="\${path:+$path }$w"
  done
  completions=()
  case "$path" in
${cases}
  esac
  compadd -- "\${completions[@]}"
}
_${name} "$@"
`;
}

export function generateFishCompletion(root: Command): string {
  const name = programName(root);
  const completes = collectCompletionNodes(root)
    .map((n) => `complete -c ${name} -n '__${name}_using "${n.path}"' -a '${n.words.join(' ')}'`)
    .join('\n');

  return `# Fish completion for ${name} (Prisma AIRS CLI). Generated by \`${name} completion fish\`.
#
# Install: ${name} completion fish > ~/.config/fish/completions/${name}.fish

function __${name}_using
    set -l target $argv[1]
    set -l tokens (commandline -opc)
    set -l path
    for w in $tokens[2..-1]
        string match -q -- '-*' $w
        and continue
        set -a path $w
    end
    test "$path" = "$target"
end

complete -c ${name} -f
${completes}
`;
}

const GENERATORS: Record<CompletionShell, (root: Command) => string> = {
  bash: generateBashCompletion,
  zsh: generateZshCompletion,
  fish: generateFishCompletion,
};

export function registerCompletionCommand(program: Command): void {
  program
    .command('completion <shell>')
    .description('Generate a shell completion script (bash, zsh, fish)')
    .addHelpText(
      'after',
      examples(
        'airs completion bash > ~/.local/share/bash-completion/completions/airs',
        'mkdir -p ~/.zfunc && airs completion zsh > ~/.zfunc/_airs',
        'airs completion fish > ~/.config/fish/completions/airs.fish',
      ),
    )
    .action((shell: string) => {
      const generate = GENERATORS[shell as CompletionShell];
      if (!generate) {
        usageError(`Unsupported shell "${shell}". Valid shells: ${COMPLETION_SHELLS.join(', ')}`);
      }
      // stdout only — the script is the data payload.
      console.log(generate(program));
    });
}
